### PR TITLE
instructions for v2 build

### LINKED ISSUE #240: No documenation for installing v2 locally
I am not sure how to create the build after doing a clone and a pip requirements.

```
~/bulk-downloader-for-reddit$ python3 setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

### PR DESCRIPTION
**Pull request by cgsmith**
Fixes #240 

Related to #218

### CODE REVIEW

**Comment by Serene-Arc** [comment]
I believe that this PR is premature. This part of the README will be added when the beta is over and will link to the pypi package that is downloadable with pip. That is preferable for the bulk of people, and these instructions are not hard to find in any case as this is the standard way to install a package from source.

**Comment by cgsmith** [comment]
@Serene-Arc if the instructions were not necessary this issue wouldn't pop up again. A lot of developers may want to contribute but aren't familiar with Python's build process (like me). Having some documentation encourages future growth and participation from a larger community. 

I can put this in a contribution section.

**Comment by Serene-Arc** [comment]
I think the contributing document would be a better place for it. I don't want regular users getting confused and installing this way because it's not optimal for a couple of reasons. But if developers need it then the contributing docs would be the place. 

Also the best command would be ‘python3 -m pip install -e .’ This installs the package while remaining linked to the source so any changes to the code can be tested without reinstalling.

**Comment by aliparlakci** [comment]
This PR can be merged if the necessary steps to setup the environment for development are provided in the contributions doc.

**Comment by mchubby** [comment]
Not a build error per se, but it seems Python 3.9  is the minimal requirement for running the script.

I get this error from a 3.8 venv:
TypeError: 'type' object is not subscriptable

**Comment by Serene-Arc** [comment]
Yes I believe there were a couple typing hints that are only available in 3.9 onwards

**Pull request closed without merging**
