### PR TITLE
This allows to download gallerys/multiple images in posts

### PR DESCRIPTION
**Pull request by Creepler13**

### CODE REVIEW

**Comment by JanDevDE** [comment]
@Creepler13 Getting

"GETTING POSTS
• 'NoneType' object is not iterable"

with your version compared to the master branch

**Comment by Creepler13** [comment]
Could you tell what you tried to download, because i'm having trouble to recreate this error

**Review by 4DeepThought2 — APPROVED** [review]
Ive tested these changes in latest, and they work.

**Comment by PotatoLord73** [comment]
I have very little coding experience, how do I add this to the program?

**Comment by vladdoster** [comment]
@PotatoLord73 would you mind opening an issue with your question? This would allow others who might have the same question find the answer I will give you.

**Pull request merged**
