### PR TITLE
Add logic to handle mobile youtube (m.youtube) links.

### PR DESCRIPTION
**Pull request by BlipRanger**
Quick edit to support mobile youtube links. Discovered while tested and confirmed to work against m.youtube links.

### CODE REVIEW

**Comment by aliparlakci** [comment]
Necessary tests should also be added

**Review by aliparlakci — CHANGES_REQUESTED** [review]
Necessary tests should also be added

**Comment by Serene-Arc** [comment]
This needs tests, also please modify the existing YouTube regex to avoid adding another entry that is superfluous. Since the factory is likely to grow, keeping it as small as is feasible would be good. `r'(m\.)?youtu\.?be` would do the same thing in the same entry

**Review by Serene-Arc — CHANGES_REQUESTED** [review]
Also please modify the existing YouTube regex to avoid adding another entry that is superfluous. Since the factory is likely to grow, keeping it as small as is feasible would be good. `r'(m\.)?youtu\.?be` would do the same thing in the same entry

**Comment by BlipRanger** [comment]
Alright, made that small change and added a test. Was there another one needed or does that cover it?

**Review by Serene-Arc — APPROVED** [review]
Looks fine to me, merging

**Pull request merged**
