### PR TITLE
add functionality for TOP and use time_filter in search

### LINKED ISSUE #269: option --sort not working in v2
the command is downloading off the "hot" page as is evident by the two pinned posts being downloaded. this week's top r/RATS posts are all images (and not the same ones being downloaded)

command run:
```
python3.9 -m bdfr download ~/dl/screensaver -S top --time week -s RATS -L 3
```

log file:
```
cat ~/Library/Application\ Support/bdfr/log_output.txt
```

```
[2021-04-16 23:11:55,054 - bdfr.downloader - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-04-16 23:11:55,054 - bdfr.downloader - Level 9] - Created download filter
[2021-04-16 23:11:55,054 - bdfr.downloader - Level 9] - Created time filter
[2021-04-16 23:11:55,054 - bdfr.downloader - Level 9] - Created sort filter
[2021-04-16 23:11:55,054 - bdfr.downloader - Level 9] - Create file name formatter
[2021-04-16 23:11:55,054 - bdfr.downloader - DEBUG] - Using unauthenticated Reddit instance
[2021-04-16 23:11:55,054 - bdfr.downloader - Level 9] - Created site authenticator
[2021-04-16 23:11:55,055 - bdfr.downloader - DEBUG] - Added submissions from subreddit RATS
[2021-04-16 23:11:55,055 - bdfr.downloader - Level 9] - Retrieved subreddits
[2021-04-16 23:11:55,055 - bdfr.downloader - Level 9] - Retrieved multireddits
[2021-04-16 23:11:55,055 - bdfr.downloader - Level 9] - Retrieved user data
[2021-04-16 23:11:55,055 - bdfr.downloader - Level 9] - Retrieved submissions for given links
[2021-04-16 23:11:55,507 - bdfr.downloader - DEBUG] - Attempting to download submission 6ez446
[2021-04-16 23:11:55,512 - bdfr.downloader - DEBUG] - Using SelfPost with url https://www.reddit.com/r/RATS/comments/6ez446/rattit_gets_discord/
[2021-04-16 23:11:55,673 - bdfr.downloader - DEBUG] - Written file to /Users/garg/Downloads/screensaver/RATS/WeAreLegionWeAreMany_Rattit gets Discord!_6ez446.txt
[2021-04-16 23:11:55,673 - bdfr.downloader - DEBUG] - Hash added to master list: 97ee82d33f84d02c4a8583a5ee6317c8
[2021-04-16 23:11:55,674 - bdfr.downloader - INFO] - Downloaded submission 6ez446 from RATS
[2021-04-16 23:11:55,674 - bdfr.downloader - DEBUG] - Attempting to download submission ghmdsn
[2021-04-16 23:11:55,674 - bdfr.downloader - DEBUG] - Using SelfPost with url https://www.reddit.com/r/RATS/comments/ghmdsn/rattits_posting_rules/
[2021-04-16 23:11:55,803 - bdfr.downloader - DEBUG] - Written file to /Users/garg/Downloads/screensaver/RATS/WeAreLegionWeAreMany_Rattit's Posting Rules_ghmdsn.txt
[2021-04-16 23:11:55,803 - bdfr.downloader - DEBUG] - Hash added to master list: 18d6cc1a3a129a5bc6c30a077bdf2c80
[2021-04-16 23:11:55,803 - bdfr.downloader - INFO] - Downloaded submission ghmdsn from RATS
[2021-04-16 23:11:55,803 - bdfr.downloader - DEBUG] - Attempting to download submission msbw6l
[2021-04-16 23:11:55,803 - bdfr.downloader - DEBUG] - Using Direct with url https://i.redd.it/vjsjh881jlt61.jpg
[2021-04-16 23:11:55,932 - bdfr.downloader - DEBUG] - Written file to /Users/garg/Downloads/screensaver/RATS/abpsych_Rats bring me joy_msbw6l.jpg
[2021-04-16 23:11:55,932 - bdfr.downloader - DEBUG] - Hash added to master list: 5f112bb0c77b6b6a94df7073a71219e6
[2021-04-16 23:11:55,932 - bdfr.downloader - INFO] - Downloaded submission msbw6l from RATS
[2021-04-16 23:11:55,933 - root - INFO] - Program complete
```

"new" seems to be working fine though, so it's not as if the option is not being passed

### PR DESCRIPTION
**Pull request by srajangarg**
fixes #269, lemme know where else this needs to be added/fixed. i only had a cursory look at the code to fix this for my personal usecase.

### CODE REVIEW

**Review by Serene-Arc — CHANGES_REQUESTED** [review]
First off, thanks for submitting a pull request to the BDFR :) I have a couple of notes:

- Firstly, please don't make unrelated changes to files, it muddies the commit history. In this case, the default configuration file has nothing to do with your PR and shouldn't be changed
- If you're proposing to add in the time filter, please add it in all the situations where it is relevant i.e. in the subreddits, multireddits, and any other sources that can take the time filter parameter
- If you can, try to add a test that fails because of the current code and succeeds due to your changes. This will make sure that oversights like this are rarer in the future

**Comment by srajangarg** [comment]
Made the requested changes, however I will not be able to add a test at the moment.

**Comment by Serene-Arc** [comment]
According to the CI, your changes cause a great many existing tests to fail. The PR cannot be merged while this remains the case

**Comment by Serene-Arc** [comment]
Thanks for your work thus far, but given the rather vital features included here, I will be taking over this fix myself. We want to release v2.0.0 as soon as possible and this is the main bug holding it up. Thanks again for your time.

**Comment by srajangarg** [comment]
No problem, good luck with the release!

**Pull request closed without merging**
