### PR TITLE
Imgur updates

### LINKED ISSUE #662: [BUG] Imgur redirection causing html page download
## Description
Imgur redirection edge cases

### PR DESCRIPTION
**Pull request by Soulsuck24**
Update Imgur logic to cover malformed links that cause a redirect leading to the html of the page being saved as an image.

Fixes #662

### CODE REVIEW

**Comment by KylarZeppeli** [comment]
Just checked this out & it looks like Imgur & RedGifs are working perfectly now, the 2 links I posted now download properly, & RedGifs was already fixed.
I'm new to GitHub, what has to happen to make your edits be part of the main repo?

**Comment by Serene-Arc** [comment]
I have to check it and merge it. I'm busy with studies at the moment but I'm going to try merging a bunch of stuff and doing a release in the next few days.

**Comment by KylarZeppeli** [comment]
Forgive me if this isn't how it works but the bdfr/site_downloaders/download_factory.py file from this pull request has made the RedGifs redirect links download as HTML with .jpg extensions again. (Imgur works perfectly)
 I replaced it with the download_factory.py file from https://github.com/Soulsuck24/bulk-downloader-for-reddit/commit/2f2b5b749c7348be09babc31e26fac6c2c243716
This one has every Imgur link download as HTML with .gifv extension. (RedGifs works perfectly)

**Comment by Soulsuck24** [comment]
This only contains the Imgur changes so to have both you will need to manually combine the changes from both until Serene can check over them herself and merge them both.

**Comment by KylarZeppeli** [comment]
If that's the case then I believe you should be completely done with RedGifs & Imgur now as I have downloaded around 26,000 images from 45 subreddits again & every single file was correctly downloaded except for 56 links from RedGifs being downloaded as HTML with .jpg extension.
If that is fixed after the merge then everything should be 100% perfect.
Thanks for your help!

**Pull request merged**
