### PR TITLE
Add script to unsave posts

### PR DESCRIPTION
**Pull request by ZapperDJ**
This script brings back the functionality to unsave posts that was present on v1, but keeping it separate from the core bdfr. It is used along extract_successful_ids.sh script

### CODE REVIEW

**Comment by Serene-Arc** [comment]
If this is being added, can you please add references in the relevant documentation so that people knows it exists?

**Comment by ZapperDJ** [comment]
@Serene-Arc should I open another pull request with the changes made to the readme.md files on the root of the repo and on the scripts folder?

**Comment by Serene-Arc** [comment]
No keep them in here, this is the right place for them.

**Comment by ZapperDJ** [comment]
Added the required changes on the documentation

**Pull request merged**
