### PR TITLE
Fix error with old gfycat/redgif urls 

### LINKED ISSUE #373: [BUG] Error with old gfycat/redgif urls
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Some old gfycat links which are now part of redgifs aren't correctly downloaded. The original gfycat urls included capitalisation, unlike the new redgifs urls, causing API requests to return 404 errors.

Example: **(NSFW)**
[https://gfycat.com/TheseWearyAruanas](https://gfycat.com/TheseWearyAruanas)
resolves to 
[https://api.redgifs.com/v1/gfycats/TheseWearyAruanas](https://api.redgifs.com/v1/gfycats/TheseWearyAruanas) (404 error)
However, changing to lowercase works:
[https://api.redgifs.com/v1/gfycats/thesewearyaruanas](https://api.redgifs.com/v1/gfycats/thesewearyaruanas)

## Command
```
python3 -m bdfr download ... --user me --saved --authenticate
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.9.5

## Logs
Relevant section:
```
[2021-05-14 16:54:42,775 - bdfr.downloader - DEBUG] - Attempting to download submission 8qy0r3
[2021-05-14 16:54:42,776 - bdfr.downloader - DEBUG] - Using Gfycat with url https://gfycat.com/TheseWearyAruanas
[2021-05-14 16:54:44,255 - bdfr.downloader - ERROR] - Site Gfycat failed to download submission 8qy0r3: Server responded with 404 to https://api.redgifs.com/v1/gfycats/TheseWearyAruanas
```

### PR DESCRIPTION
**Pull request by alpbetgam**
Fixes #373, by converting to lowercase all gfycat links that redirect to redgifs.

### CODE REVIEW

**Comment by aliparlakci** [comment]
Could you rebase your commits from the latest commit on `development` branch and re-run the workflow?

**Comment by alpbetgam** [comment]
I think I've done it now, but this is my first time so I'm not completely sure.

**Review by Serene-Arc — CHANGES_REQUESTED** [review]
Hi, I can't approve these. Somehow with each commit, you delete and rewrite the entire file on which you're working. That's not okay for the history of the file. As per the contribution guidelines, please limit your changes to the lines you've directly altered.

**Comment by alpbetgam** [comment]
Sorry about that. I've tried to fix it by reverting and redoing it, so hopefully now it should look right. If this doesn't work, then I'll probably just give up.

**Review by Serene-Arc — APPROVED** [review]
Yup, this looks fine to me.

**Pull request merged**
