### PR TITLE
V2 Dockerfile

### PR DESCRIPTION
**Pull request by BlipRanger**
Added a quick dockerfile to V2 (based on V1) and made a slight change to the port binding to support running within docker.

### CODE REVIEW

**Comment by aliparlakci** [comment]
This is out of the scope of v2. However, it can be in another repository since latest version of the source code can be pulled from inside the Docker container.

**Comment by Serene-Arc** [comment]
Yes, I fail to see how running in a Docker container would improve anything about the BDFR. It isn't necessary, but if you need to for whatever reason, writing your own Dockerfile should be pretty trivial

**Comment by BlipRanger** [comment]
> 
> 
> Yes, I fail to see how running in a Docker container would improve anything about the BDFR. It isn't necessary, but if you need to for whatever reason, writing your own Dockerfile should be pretty trivial

Understood. Just noticed you guys had one in V1 and was attempt to contribute in some small way.

**Comment by Serene-Arc** [comment]
Sorry, there have been a lot of changes from v1 to v2 in the program design. You're more than welcome to host your own Dockerfile for people :)

**Pull request closed without merging**
