### PR TITLE
Adding info to threads and comments: distinguished, spoiler, pinned, locked

### LINKED ISSUE #408: [FEATURE] Adding info to threads and comments: distinguished, spoiler, pinned, locked
- [ x ] I am requesting a feature.
- [ x ] I am running the latest version of BDfR
- [ x ] I have read the [Opening an issue](../../README.md#configuration)
  
## Description

PR related: #409

This pull request adds some more data that I find useful to the Reddit threads and comments retrieved.

On threads:
- `distinguished`: Whether the thread is posted officially as an admin, a moderator, or a simple user (this is what gives the icon and the username highlight). ("admin"/"moderator"/None)
- `spoiler`: Whether the thread is marked as "spoiler" (similar to `over_18`) (True/False)
- `pinned`: Whether the thread is pinned (True/False)
- `locked`: Whether the thread is locked (True/False)

On comments:
- `distinguished`: Same as the thread, but on a comment basis

### PR DESCRIPTION
**Pull request by Ailothaen**
Closes #408

This pull request adds some more data that I find useful to the Reddit threads and comments retrieved.

On threads:
- `distinguished`: Whether the thread is posted officially as an admin, a moderator, or a simple user (this is what gives the icon and the username highlight). ("admin"/"moderator"/None)
- `spoiler`: Whether the thread is marked as "spoiler" (similar to `over_18`) (True/False)
- `pinned`: Whether the thread is pinned (True/False)
- `locked`: Whether the thread is locked (True/False)

On comments:
- `distinguished`: Same as the thread, but on a comment basis

### CODE REVIEW

**Comment by aliparlakci** [comment]
Can you rebase your branch from `development`?

**Comment by Ailothaen** [comment]
Indeed, I did the mistake to do a merge instead of a rebase in my branch...
My knowledge of Git is not great, I do not know if this is possible to rollback this. Do you have any hint, or would it be better to make another PR?

**Comment by aliparlakci** [comment]
```
$ git clone https://github.com/Ailothaen/bulk-downloader-for-reddit.git
$ cd ./bulk-downloader-for-reddit
$ git rebase -i 739f97ed
```

Change the ***Adds download count badge*** commit from `pick` to `drop`, save and close the file.

Lastly, do

```
$ git push -f origin master
```

This should solve the problem if I am not mistaken.

**Comment by Ailothaen** [comment]
Sounds to be done. Thank you for the info!

**Comment by aliparlakci** [comment]
Could you also add necessary test cases? I see that we already have `tests/archive_entry/test_submission_archive_entry.py::test_get_post_details`. You can populate it with the newly added fields and the correct expected outputs. It would be very kind of you if you could also do it for the missing fields as well :)

With the proper tests prescribing the contents of an archive entry, there will be no way of modifying the format of archive entry files "accidentally".

**Comment by Ailothaen** [comment]
Done! I added several other fields as well.

I should tell that one of the tests is constantly failing for me (`tests/site_downloaders/test_erome.py`, the 4th one)

**Review by aliparlakci — APPROVED** [review]
Looks good to me. Congrats on your first contribution!

**Pull request merged**
