### PR TITLE
Formatting cleanup

### PR DESCRIPTION
**Pull request by OMEGARAZER**
Cleanup some formatting from switch to Black

### CODE REVIEW

**Comment by OMEGARAZER** [comment]
fyi, the formatting check fails with this on my fork. Not sure if it's something you're familiar with or know why.

```
stdout: format_check run-test: commands[2] | mdl README.md docs/ -s .markdown_style.rb

stdout: /var/lib/gems/2.7.0/gems/mdl-0.12.0/lib/mdl/cli.rb:118:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
	from /var/lib/gems/2.7.0/gems/mdl-0.12.0/lib/mdl/cli.rb:118:in `run'
	from /var/lib/gems/2.7.0/gems/mdl-0.12.0/lib/mdl.rb:16:in `run'
	from /var/lib/gems/2.7.0/gems/mdl-0.12.0/bin/mdl:10:in `<top (required)>'
	from /usr/local/bin/mdl:23:in `load'
	from /usr/local/bin/mdl:23:in `<main>'

stdout: ERROR: InvocationError for command /usr/local/bin/mdl README.md docs/ -s .markdown_style.rb (exited with code 1)

stdout: ___________________________________ summary ____________________________________
stdout: 
ERROR:   format_check: commands failed
```

**Comment by Serene-Arc** [comment]
I'm not sure what's causing that, does mdl work normally for you?

**Comment by OMEGARAZER** [comment]
With Ruby and everything installed it does locally for me but not on my github branch. It doesn't stop the other tests from working. Just now get notifications for every push that it's failed when everything else passes.

**Comment by Serene-Arc** [comment]
That's weird because it works in mine and in Ali's, obviously since we were able to merge this PR with all checks green. Maybe open an issue and we can discuss it further. I know that the ruby version indicated in that stacktrace is older than the one I'm using on my PC.

**Comment by OMEGARAZER** [comment]
Yeah, same, it's older than mine as well. No clue, oh well.

**Pull request merged**
