### PR TITLE
[WIP] (maint) code clean up

### PR DESCRIPTION
**Pull request by vladdoster**
## bdfr

- Add the bound instance as method parameter
- Change methods not using its bound instance to staticmethods
- Fix dangerous default argument
- Refactor the comparison involving `not`
- Refactor unnecessary `else` / `elif` when `if` block has a `raise` statement
- Refactor unnecessary `else` / `elif` when `if` block has a `return` statement
- Refactor useless `else` block in the loop
- Remove implicit `object` from the base class
- Remove reimported module
- Remove unnecessary generator
- Remove unnecessary return statement
- Remove unnecessary use of comprehension
- Remove unused imports
- Use `is` to compare type of objects
- Using not x can cause unwanted results

## Dockerfile

- use a pinned Python version tag instead of latest
- leverage cached requirements

## GitHub Actions CI/CD 

- Tests bdfr
    1. Dockerfile
    1. MacOS
    1. Windows
    1. Ubuntu  

Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

### CODE REVIEW

**Comment by vladdoster** [comment]
Working on GH CI/CD now, will be done soon and ready for review @aliparlakci.

**Comment by aliparlakci** [comment]
there is an unpleasant problem here. @Serene-Arc has made some refactoring couple of hours ago. I decided that working on a `develop` branch and merging it to master would make it easier to maintain. So we merged those changes into the `develop` branch.

Now that you have both changed the same files, there will be a lot of merge conflicts when I try to merge to `develop`.

what do you suggest, @vladdoster?

Also, we discussed this on discord. add me and I can invite you to the channel.

**Comment by vladdoster** [comment]
> there is an unpleasant problem here. @Serene-Arc has made some refactoring couple of hours ago. I decided that working on a `develop` branch and merging it to master would make it easier to maintain. So we merged those changes into the `develop` branch.
> 
> Now that you have both changed the same files, there will be a lot of merge conflicts when I try to merge to `develop`.
> 
> what do you suggest, @vladdoster?
> 
> Also, we discussed this on discord. add me and I can invite you to the channel.

I would suggest resolving the merge conflicts. I can do it or if you want to shadow me via discord screen share as I do it that is fine with me.

**Comment by aliparlakci** [comment]
> I would suggest resolving the merge conflicts. I can do it or if you want to shadow me via discord screen share as I do it that is fine with me.

you can resolve them. there is no need for me to shadow you. thanks for offering it, also :)

**Comment by aliparlakci** [comment]
also, you can create branches on the repo instead of branches from forked repos.

**Review by aliparlakci — APPROVED** [review]
LGTM

**Comment by vladdoster** [comment]
> also, you can create branches on the repo instead of branches from forked repos.

I'd consider not working from a fork as an anti-pattern. The Forking Workflow helps a maintainer of a project open up the repository to contributions from any developer without having to manually manage authorization settings for each individual contributor. This gives the maintainer more of a "pull" style workflow. Most commonly used in open-source projects, the Forking Workflow can also be applied to private business workflows to give more authoritative control over what is merged into a release. This can be useful in teams that have Deploy Managers or strict release cycles.

I do have a reason for my madness 😃 .

**Comment by vladdoster** [comment]
It can quickly lead to a lot of stale branches if you don't stay on top of pruning them periodically.

**Comment by aliparlakci** [comment]
> > also, you can create branches on the repo instead of branches from forked repos.
> 
> I'd consider not working from a fork as an anti-pattern. The Forking Workflow helps a maintainer of a project open up the repository to contributions from any developer without having to manually manage authorization settings for each individual contributor. This gives the maintainer more of a "pull" style workflow. Most commonly used in open-source projects, the Forking Workflow can also be applied to private business workflows to give more authoritative control over what is merged into a release. This can be useful in teams that have Deploy Managers or strict release cycles.
> 
> It can quickly lead to a lot of stale branches if you don't stay on top of pruning them periodically.
> 
> I do have a reason for my madness 😃 .

I have been using gitflow in small, private teams for a fair amount of time. However, I have little experience with open-source projects and did not know The Forking Workflow existed.

Having a read about the forking workflow, it will suit this project better than gitflow. So we can continue with forking.

Thanks for the info 👍🏻

**Comment by Serene-Arc** [comment]
I think this commit is problematic at the moment. Much of it is either obsolete from the new branch and or will be when the refactoring is complete. I went through the whole project and changed most of it to conform to the PEP8 standard which seems to be most of what this is. The remainder of it will be dealt with in the refactor, most likely, but it's hard to tell when there's so many unrelated changes in a single commit. Assuming I can begin my refactor in the next few hours as intended, there isn't likely to be much relationship with the code in this commit and the code in my refactor, so merging will be incredibly difficult.

**Pull request merged**
