### PR TITLE
2.6.1

### PR DESCRIPTION
**Pull request by OMEGARAZER**
With the number of fixes and changes (There's a non-working module in 2.6.0), it's probably a good idea to get a release out.

It also would leave a good starting point to work toward #703 and any other automatic linting/formatting.

### CODE REVIEW

**Comment by Serene-Arc** [comment]
Before a release can be done, all of the tests have to be 100% working. @Soulsuck24 do you have any idea why the RedGifs MacOS tests are failing? I believe that you were the last to change that module, with a lot of changes.

**Comment by Soulsuck24** [comment]
Taking a look through at where they're failing and where they're not it doesn't look like it's anything wrong on BDFR's end. They'll fail one run and then succeed the next with no changes to the running code (passes https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/708/commits/b30ced9be958da5483427b0f40f8473cdcdc91ff but not https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/708/commits/0a3b3d7b7c206094eefc5dea2e47b948b6a25e25 or failing https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/708/commits/175513fbb70054623d448259acebbacc2b06c61f but succeeding https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/708/commits/7b7167643f74ab17744cae31c015a5f870ecec60 with the only change being the README.md). Are you able to re-run that test in particular to check it?

That said, I will look and see if I can figure anything out to make it sturdier but it doesn't look like it's on this side.

**Comment by Serene-Arc** [comment]
@Soulsuck24 they only seem to be failing on MacOS, which isn't my specialty. The other ones work fine, but the RedGifs module errors out with 403 errors

**Comment by Soulsuck24** [comment]
Well, I got a Mac VM set up and I have yet to have a test fail. All passing with no issues. Like I mentioned, it doesn't seem like it's an issue on BDFR's side. Even my own pull of the most recent commits passes fine https://github.com/Soulsuck24/bulk-downloader-for-reddit/commit/0a3b3d7b7c206094eefc5dea2e47b948b6a25e25 while the same commit didn't pass here.
Screen Shot 2022-12-02 at 5 05 43 PM
I'd say at this point if the test isn't able to be re-run then we just need to wait for another commit that will run the test again and hope it doesn't mess it up again.

**Comment by Serene-Arc** [comment]
Weird. Alright, I'll figure something out.

**Pull request merged**
